name: Doxygen

on:
  push:
    branches: [ main ]

jobs:
  build-documentation:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: |
       pwd
       git clone https://github.com/jiaqiwang969/dune-learning.git
                
    - name: Build Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "./dune-learning/doc"
        
    # Deploy the HTML documentation to GitHub Pages
    - name: Publish Doxygen documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dune-learning/doc/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages