name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: download
        run: |
         git clone https://github.com/jiaqiwang969/dune-course-material.git
         cd dune-course-material
         tar -zxvf iwr-course-2021.tar.gz


      - name: install
        run: |
         cd iwr-course-2021
         ./install.sh

        

      # - name: Publish Doxygen documentation
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: dealii/doc
      #     enable_jekyll: false
      #     allow_empty_commit: false
      #     force_orphan: true
      #     publish_branch: gh-pages

      # - name: test
      #   run: |
      #     cd dealii
      #     make setup_tests_hello
      #     make setup_tests_mystl_test
      #     ctest 

      # - name: collect code coverage
      # run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"



